# -*- coding: utf-8 -*-
{
    'name': 'Website Dismac',
    'version': '12.0.0.2.0',
    'summary': 'Customization for Dismac website.',
    'description': '',
    'category': 'Website',
    'author': 'Comunitea',
    'contributors': [
        'Rubén Seijas <ruben@comunitea.com>',
        'Vicente Gutiérrez, <vicente@comunitea.com>',
    ],
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    "price": 0,
    "currency": "EUR",
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    'installable': True,
    'application': False,
    "live_test_url": "",
    "demo": [],
    "demo_title": "",
    "demo_addons": [],
    "demo_addons_hidden": [],
    "demo_url": "",
    "demo_summary": "",
    "demo_images": [],
    "external_dependencies": {
        "python": [], "bin": []
    },
    'depends': [
        'account',
        'partner_statement',
        'web',
        'website',
        'website_canonical_url',
        'website_cookie_notice',
        'website_form',
        'website_legal_page',
        'website_menu_by_user_status',
        'website_sale',
        # Custom
        'website_base',
        'website_seo_settings',
        # Licences
        # 'sgeede_infinite_scroll',
    ],
    'data': [
        'data/website_data.xml',
        'data/menu_data.xml',
        'data/default_data.xml',
        'templates/account.xml',
        'templates/head.xml',
        'templates/forms.xml',
        'templates/cookies.xml',
        'templates/footer.xml',
        'templates/product.xml',
        # 'templates/simulated_product.xml',
        'views/customize_views.xml',
        'templates/sale_order_portal.xml',
        'security/ir.model.access.csv'
    ],
    'images': [
        '/static/description/icon.png',
    ],
    'qweb': [
    ],
}
