# -*- coding: utf-8 -*-
{
    'name': 'Dismac Theme',
    'version': '1.0',
    'summary': 'Frontend customization for Dismac Website',
    'description': '',
    'category': 'Theme/Ecommerce',
    'author': 'Comunitea',
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    'contributors': [
        'Vicente Gutiérrez, <vicente@comunitea.com>',
        'Rubén Seijas <ruben@comunitea.com>',
    ],
    'depends': [
        'website',
        'website_base',
        'website_theme_install',
    ],
    'data': [
        'data/menu_data.xml',
        # 'data/page_data.xml',
        'templates/head.xml',
        # 'templates/header.xml',
        'templates/footer.xml',
        # 'templates/legal.xml',
        # 'templates/page_home.xml',
        # 'templates/page_work_with_us.xml',
        # 'templates/page_about_us.xml',
        # 'templates/page_contact_us.xml',
        # 'templates/page_contact_us_thanks.xml',
        # 'templates/page_our_shops.xml',
        # 'templates/page_open_shop.xml',
        # 'templates/page_delivery_and_payment.xml',
        # 'templates/page_our_group.xml',
        # 'templates/shop.xml',
        # 'templates/product.xml',
        # 'templates/newsletter.xml',
        # 'templates/pages.xml',
        # 'views/customize_views.xml',
    ],
    'images': [
        '/static/description/theme_dismac.png',
        '/static/description/theme_dismac_screenshot.png',

    ],
    'qweb': [
    ],
    'installable': True,
    'application': False,
}
