# -*- coding: utf-8 -*-
{
    'name': 'MultiWebsite Base Module',
    'version': '1.0',
    'summary': 'Backend customization for all companies and their websites.',
    'description': '',
    'category': 'Website',
    'author': 'Comunitea',
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    'contributors': [
        'Rubén Seijas <ruben@comunitea.com>',
        'Vicente Gutiérrez, <vicente@comunitea.com>',
    ],
    'depends': [
        'ecommerce_base',
        # 'seo_base',
        'breadcrumbs_base_tmp',
        # 'website_blog_base',
        # 'follow_us_base',
        # 'multi_company_base',
        # 'mass_mailing',
        # 'website_form_builder',
        # 'website_sale_product_brand',
        # 'payment_redsys',
        # 'website_sale_hide_price',
        # 'rest_api_dismac',
    ],
    'data': [
        'data/website_data.xml',
        'templates/account.xml',
        'templates/forms.xml',
        'templates/head.xml',
        # 'templates/cart.xml',
        'templates/header.xml',
        # 'templates/shop.xml',
        # 'templates/product.xml',
        # 'templates/newsletter.xml',
        # 'templates/portal.xml',
        # 'templates/wishlist.xml',
        # 'views/product_attribute.xml',
        # 'views/res_company_views.xml',
        # 'views/website_views.xml',
        # 'views/public_category.xml',
        # 'views/product_template.xml',
        # 'views/res_config_settings_views.xml',
        # 'views/blog_blog.xml',
        # 'views/blog_post_view.xml',
        # 'security/ir.model.access.csv',
    ],
    'images': [
        '/static/description/icon.png',
    ],
    'qweb': [
    ],
    'installable': True,
    'application': False,
}
