# -*- coding: utf-8 -*-
{
    'name': 'MultiWebsite Base Module',
    'version': '12.0.0.2.0',
    'summary': 'Backend customization for all companies and their websites.',
    'description': '',
    'category': 'Website',
    'author': 'Comunitea',
    'contributors': [
        'Rubén Seijas <ruben@comunitea.com>',
    ],
    'website': 'http://www.comunitea.com',
    'license': 'AGPL-3',
    "price": 0,
    "currency": "EUR",
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    'installable': True,
    'application': False,
    "live_test_url": "",
    "demo": [],
    "demo_title": "",
    "demo_addons": [],
    "demo_addons_hidden": [],
    "demo_url": "",
    "demo_summary": "",
    "demo_images": [],
    "external_dependencies": {
        "python": [], "bin": []
    },
    'depends': [
        'base',
        'website_sale',
        'ecommerce_base',
        'website_seo_settings',
        'breadcrumbs_base_tmp',
        'sale_order_lock',
        'product_supplierinfo_for_customer',
        'website_sale_checkout_skip_payment',
        'base_tier_validation'
    ],
    'data': [
        'templates/head.xml',
        'templates/forms.xml',
        'templates/header.xml',
        'templates/simulated_products.xml',
        'templates/offer.xml',
        'templates/product.xml',
        'templates/quote.xml',
        'templates/portal_history.xml',
        'templates/portal_reviews.xml',
        'templates/pending_validation.xml',
        'templates/checkout.xml',
        'templates/portal.xml',
        'templates/cart.xml',
        'views/product_views.xml',
        'views/quote_views.xml',
        'security/ir.model.access.csv',
        'security/sale_security.xml',
        'templates/payment.xml',
        'views/res_partner.xml',
        'wizard/res_partner_wzd.xml',
        'wizard/portal_wizard_views.xml',
    ],
    'images': [
        '/static/description/icon.png',
    ],
    'qweb': [
    ],
}
